DROP DATABASE IF EXISTS blogDatabase;

CREATE DATABASE IF NOT EXISTS blogDatabase;

USE blogDatabase;

CREATE TABLE IF NOT EXISTS RegisteredUser (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    firstname VARCHAR(50) NOT NULL,
    familyname VARCHAR(50) NOT NULL,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL DEFAULT '1234',
    email VARCHAR(50) NOT NULL UNIQUE,
    access ENUM ('admin', 'moderator', 'user') DEFAULT 'user',
    reg_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS BlogWritten (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    user_ID INT,
    blog_schemas_name VARCHAR(20) DEFAULT 'none',
    blog_schemas LONGBLOB,
    blog_color ENUM ('red', 'blue', 'black') DEFAULT 'black',
    blog_text VARCHAR(16000) NOT NULL, 
    entry_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID),
    FOREIGN KEY(ID) REFERENCES RegisteredUser(ID)
);

CREATE TABLE IF NOT EXISTS CommentBlog (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    blog_ID INT,
    comment_reply_ID INT DEFAULT 0,
    user_ID INT,
    comment_text VARCHAR(10000) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY(ID) REFERENCES BlogWritten(ID),
    FOREIGN KEY(ID) REFERENCES CommentBlog(ID),
    FOREIGN KEY(ID) REFERENCES RegisteredUser(ID)
);
    
CREATE TABLE IF NOT EXISTS BlogToUser (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    user_ID INT UNSIGNED NOT NULL,
    blog_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(user_ID) REFERENCES RegisteredUser(ID),
    FOREIGN KEY(blog_ID) REFERENCES BlogWritten(ID)
);

CREATE TABLE IF NOT EXISTS CommentToBlog (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    blog_ID INT UNSIGNED NOT NULL,
    comment_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(blog_ID) REFERENCES BlogWritten(ID),
    FOREIGN KEY(comment_ID) REFERENCES CommentBlog(ID)
);
	
CREATE TABLE IF NOT EXISTS CommentToComment (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    comment_ID INT UNSIGNED NOT NULL,
    previous_comment_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(comment_ID) REFERENCES CommentBlog(ID),
    FOREIGN KEY(previous_comment_ID) REFERENCES CommentBlog(ID)
);   

CREATE TABLE IF NOT EXISTS UserCommentBlog (
	ID INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	user_id INT UNSIGNED NOT NULL,
    blog_id INT UNSIGNED NOT NULL,
    comment_ID INT UNSIGNED NOT NULL,
    previous_comment_ID INT UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(user_ID) REFERENCES RegisteredUser(ID),
    FOREIGN KEY(blog_ID) REFERENCES BlogWritten(ID),
    FOREIGN KEY(comment_ID) REFERENCES CommentBlog(ID),
    FOREIGN KEY(previous_comment_ID) REFERENCES CommentBlog(ID)
);